/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ComplianceDocumentCreateNestedManyWithoutDriversInput } from "./ComplianceDocumentCreateNestedManyWithoutDriversInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { LoadOfferCreateNestedManyWithoutDriversInput } from "./LoadOfferCreateNestedManyWithoutDriversInput";
import { MessageCreateNestedManyWithoutDriversInput } from "./MessageCreateNestedManyWithoutDriversInput";
import { NotificationCreateNestedManyWithoutDriversInput } from "./NotificationCreateNestedManyWithoutDriversInput";
import { PaymentCreateNestedManyWithoutDriversInput } from "./PaymentCreateNestedManyWithoutDriversInput";

@InputType()
class DriverCreateInput {
  @ApiProperty({
    required: false,
    type: () => ComplianceDocumentCreateNestedManyWithoutDriversInput,
  })
  @ValidateNested()
  @Type(() => ComplianceDocumentCreateNestedManyWithoutDriversInput)
  @IsOptional()
  @Field(() => ComplianceDocumentCreateNestedManyWithoutDriversInput, {
    nullable: true,
  })
  complianceDocuments?: ComplianceDocumentCreateNestedManyWithoutDriversInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  insurance?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  itinerary?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  licenseNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => LoadOfferCreateNestedManyWithoutDriversInput,
  })
  @ValidateNested()
  @Type(() => LoadOfferCreateNestedManyWithoutDriversInput)
  @IsOptional()
  @Field(() => LoadOfferCreateNestedManyWithoutDriversInput, {
    nullable: true,
  })
  loadOffers?: LoadOfferCreateNestedManyWithoutDriversInput;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutDriversInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutDriversInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutDriversInput, {
    nullable: true,
  })
  messages?: MessageCreateNestedManyWithoutDriversInput;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutDriversInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutDriversInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutDriversInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutDriversInput;

  @ApiProperty({
    required: false,
    type: () => PaymentCreateNestedManyWithoutDriversInput,
  })
  @ValidateNested()
  @Type(() => PaymentCreateNestedManyWithoutDriversInput)
  @IsOptional()
  @Field(() => PaymentCreateNestedManyWithoutDriversInput, {
    nullable: true,
  })
  payments?: PaymentCreateNestedManyWithoutDriversInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;
}

export { DriverCreateInput as DriverCreateInput };
