/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LoadOfferService } from "../loadOffer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LoadOfferCreateInput } from "./LoadOfferCreateInput";
import { LoadOffer } from "./LoadOffer";
import { LoadOfferFindManyArgs } from "./LoadOfferFindManyArgs";
import { LoadOfferWhereUniqueInput } from "./LoadOfferWhereUniqueInput";
import { LoadOfferUpdateInput } from "./LoadOfferUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LoadOfferControllerBase {
  constructor(
    protected readonly service: LoadOfferService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LoadOffer })
  @nestAccessControl.UseRoles({
    resource: "LoadOffer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLoadOffer(
    @common.Body() data: LoadOfferCreateInput
  ): Promise<LoadOffer> {
    return await this.service.createLoadOffer({
      data: {
        ...data,

        dispatcher: data.dispatcher
          ? {
              connect: data.dispatcher,
            }
          : undefined,

        driver: data.driver
          ? {
              connect: data.driver,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,
        description: true,

        dispatcher: {
          select: {
            id: true,
          },
        },

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LoadOffer] })
  @ApiNestedQuery(LoadOfferFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LoadOffer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async loadOffers(@common.Req() request: Request): Promise<LoadOffer[]> {
    const args = plainToClass(LoadOfferFindManyArgs, request.query);
    return this.service.loadOffers({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        description: true,

        dispatcher: {
          select: {
            id: true,
          },
        },

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LoadOffer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LoadOffer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async loadOffer(
    @common.Param() params: LoadOfferWhereUniqueInput
  ): Promise<LoadOffer | null> {
    const result = await this.service.loadOffer({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        description: true,

        dispatcher: {
          select: {
            id: true,
          },
        },

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LoadOffer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LoadOffer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLoadOffer(
    @common.Param() params: LoadOfferWhereUniqueInput,
    @common.Body() data: LoadOfferUpdateInput
  ): Promise<LoadOffer | null> {
    try {
      return await this.service.updateLoadOffer({
        where: params,
        data: {
          ...data,

          dispatcher: data.dispatcher
            ? {
                connect: data.dispatcher,
              }
            : undefined,

          driver: data.driver
            ? {
                connect: data.driver,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,
          description: true,

          dispatcher: {
            select: {
              id: true,
            },
          },

          driver: {
            select: {
              id: true,
            },
          },

          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LoadOffer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LoadOffer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLoadOffer(
    @common.Param() params: LoadOfferWhereUniqueInput
  ): Promise<LoadOffer | null> {
    try {
      return await this.service.deleteLoadOffer({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          description: true,

          dispatcher: {
            select: {
              id: true,
            },
          },

          driver: {
            select: {
              id: true,
            },
          },

          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
