/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ComplianceDocument } from "./ComplianceDocument";
import { ComplianceDocumentCountArgs } from "./ComplianceDocumentCountArgs";
import { ComplianceDocumentFindManyArgs } from "./ComplianceDocumentFindManyArgs";
import { ComplianceDocumentFindUniqueArgs } from "./ComplianceDocumentFindUniqueArgs";
import { CreateComplianceDocumentArgs } from "./CreateComplianceDocumentArgs";
import { UpdateComplianceDocumentArgs } from "./UpdateComplianceDocumentArgs";
import { DeleteComplianceDocumentArgs } from "./DeleteComplianceDocumentArgs";
import { Dispatcher } from "../../dispatcher/base/Dispatcher";
import { Driver } from "../../driver/base/Driver";
import { ComplianceDocumentService } from "../complianceDocument.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ComplianceDocument)
export class ComplianceDocumentResolverBase {
  constructor(
    protected readonly service: ComplianceDocumentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ComplianceDocument",
    action: "read",
    possession: "any",
  })
  async _complianceDocumentsMeta(
    @graphql.Args() args: ComplianceDocumentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ComplianceDocument])
  @nestAccessControl.UseRoles({
    resource: "ComplianceDocument",
    action: "read",
    possession: "any",
  })
  async complianceDocuments(
    @graphql.Args() args: ComplianceDocumentFindManyArgs
  ): Promise<ComplianceDocument[]> {
    return this.service.complianceDocuments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ComplianceDocument, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ComplianceDocument",
    action: "read",
    possession: "own",
  })
  async complianceDocument(
    @graphql.Args() args: ComplianceDocumentFindUniqueArgs
  ): Promise<ComplianceDocument | null> {
    const result = await this.service.complianceDocument(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ComplianceDocument)
  @nestAccessControl.UseRoles({
    resource: "ComplianceDocument",
    action: "create",
    possession: "any",
  })
  async createComplianceDocument(
    @graphql.Args() args: CreateComplianceDocumentArgs
  ): Promise<ComplianceDocument> {
    return await this.service.createComplianceDocument({
      ...args,
      data: {
        ...args.data,

        dispatcher: args.data.dispatcher
          ? {
              connect: args.data.dispatcher,
            }
          : undefined,

        driver: args.data.driver
          ? {
              connect: args.data.driver,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ComplianceDocument)
  @nestAccessControl.UseRoles({
    resource: "ComplianceDocument",
    action: "update",
    possession: "any",
  })
  async updateComplianceDocument(
    @graphql.Args() args: UpdateComplianceDocumentArgs
  ): Promise<ComplianceDocument | null> {
    try {
      return await this.service.updateComplianceDocument({
        ...args,
        data: {
          ...args.data,

          dispatcher: args.data.dispatcher
            ? {
                connect: args.data.dispatcher,
              }
            : undefined,

          driver: args.data.driver
            ? {
                connect: args.data.driver,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ComplianceDocument)
  @nestAccessControl.UseRoles({
    resource: "ComplianceDocument",
    action: "delete",
    possession: "any",
  })
  async deleteComplianceDocument(
    @graphql.Args() args: DeleteComplianceDocumentArgs
  ): Promise<ComplianceDocument | null> {
    try {
      return await this.service.deleteComplianceDocument(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Dispatcher, {
    nullable: true,
    name: "dispatcher",
  })
  @nestAccessControl.UseRoles({
    resource: "Dispatcher",
    action: "read",
    possession: "any",
  })
  async getDispatcher(
    @graphql.Parent() parent: ComplianceDocument
  ): Promise<Dispatcher | null> {
    const result = await this.service.getDispatcher(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Driver, {
    nullable: true,
    name: "driver",
  })
  @nestAccessControl.UseRoles({
    resource: "Driver",
    action: "read",
    possession: "any",
  })
  async getDriver(
    @graphql.Parent() parent: ComplianceDocument
  ): Promise<Driver | null> {
    const result = await this.service.getDriver(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
