/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ComplianceDocumentCreateNestedManyWithoutDispatchersInput } from "./ComplianceDocumentCreateNestedManyWithoutDispatchersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { LoadOfferCreateNestedManyWithoutDispatchersInput } from "./LoadOfferCreateNestedManyWithoutDispatchersInput";
import { MessageCreateNestedManyWithoutDispatchersInput } from "./MessageCreateNestedManyWithoutDispatchersInput";
import { NotificationCreateNestedManyWithoutDispatchersInput } from "./NotificationCreateNestedManyWithoutDispatchersInput";
import { PaymentCreateNestedManyWithoutDispatchersInput } from "./PaymentCreateNestedManyWithoutDispatchersInput";

@InputType()
class DispatcherCreateInput {
  @ApiProperty({
    required: false,
    type: () => ComplianceDocumentCreateNestedManyWithoutDispatchersInput,
  })
  @ValidateNested()
  @Type(() => ComplianceDocumentCreateNestedManyWithoutDispatchersInput)
  @IsOptional()
  @Field(() => ComplianceDocumentCreateNestedManyWithoutDispatchersInput, {
    nullable: true,
  })
  complianceDocuments?: ComplianceDocumentCreateNestedManyWithoutDispatchersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => LoadOfferCreateNestedManyWithoutDispatchersInput,
  })
  @ValidateNested()
  @Type(() => LoadOfferCreateNestedManyWithoutDispatchersInput)
  @IsOptional()
  @Field(() => LoadOfferCreateNestedManyWithoutDispatchersInput, {
    nullable: true,
  })
  loadOffers?: LoadOfferCreateNestedManyWithoutDispatchersInput;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutDispatchersInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutDispatchersInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutDispatchersInput, {
    nullable: true,
  })
  messages?: MessageCreateNestedManyWithoutDispatchersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nationalId?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutDispatchersInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutDispatchersInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutDispatchersInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutDispatchersInput;

  @ApiProperty({
    required: false,
    type: () => PaymentCreateNestedManyWithoutDispatchersInput,
  })
  @ValidateNested()
  @Type(() => PaymentCreateNestedManyWithoutDispatchersInput)
  @IsOptional()
  @Field(() => PaymentCreateNestedManyWithoutDispatchersInput, {
    nullable: true,
  })
  payments?: PaymentCreateNestedManyWithoutDispatchersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;
}

export { DispatcherCreateInput as DispatcherCreateInput };
